class Item < ActiveRecord::Base

  validates :name, length: {maximum: 50}, presence: true
  validates :description, length: {maximum: 250}
  validates :user_id, presence: true

  has_attached_file :photo, :styles => { :medium => "300x300>", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/

  OCCASIONS = ['n/a', '4th July', 'Anniversary', 'Christmas', 'Earth Day', 'Grand Opening', 'Halloween', 'New Year', 'St. Patrick\'s Day', 'Valentine\'s Day', 'Staff']

  LOCATIONS = %w[n/a Acapulco Albuquerue_Hotel Almaty Amman Amsterdam Anchorage Andheri Angkor Ankara Antwerp Aruba Aspen Athens Atlanta Atlantic_City Austin Bahrain Bali Bali_Hotel Baltimore Banff Bangkok Barcelona Beijing Beirut Belfast Belo_Horizonte Bengaluru Berlin Biloxi Biloxi_Hotel Birmingham Bogota Boston Bristol Brussels Bucharest Budapest Buenos Aires Cabo_San_Lucas Cairo Calgary Cancun Cancun_Hotel Cape_Town Caracas Cardiff Cartagena Catania Cayman_Islands Chennai Chicago Chicago_Hotel Choctaw Cleveland Cologne Copenhagen Costa_Maya Cozumel Dallas Denver Destin Detroit Dubai Dublin Edinburgh Edmonton Fiji Florence Four_Winds Foxwoods Ft._Lauderdale Fukuoka Gatlinburg Gdansk Glasgow Glyfada Gothenburg Gran_Canaria Guadalajara Guam Guangzhou Guatemala_City Gurgaon Hamburg Helsinki Ho_Cho_Minh_City Hollywood,_CA Hollywood,_FL Hollywood_Hotel,_FL Hollywood_Universal,_CA Hong_Kong Honolulu Houston Hurghada Hyderabad Ibiza Ibiza_Hotel Indianapolis Istanbul Jakarta Johannesburg Kanata Key_West Kobe Kona Kowloon Krakow Kuala Lumpur Kuwait La_Jolla Lake_Tahoe Las_Vegas Las_Vegas_Hotel Leeds Lima Lisbon London London_Casino Los_Angeles Louisville Macau Macau_Hotel Madrid Makati Mall_Of_America Mallorca Malta_Bar_Valletta Malta Managua Manchester Manchester_Casino Marbella Margarita Maui Medellin Melaka Melbourne Memphis Mexico_City Miami Minneapolis Montreal Moscow Mumbai Munich Myrtle_Beach Nabq Nagoya Narita Nashville Nassau New_Delhi New_Orleans New_York Newport_Beach Niagara_Falls,_NY Niagara_Falls,_ON Nice Nicosia Northfield_Park Northfield_Park_Hotel Nottingham Oasis Ocho_Rios Orlando Orlando_Hotel Osaka_Universal Osaka Oslo Ottawa Palm_Springs Panama Panama_Hotel Paris Pattaya Pattaya_Hotel Penang Penang_Hotel Philadelphia Phoenix Phuket Pigeon_Forge Pittsburgh Prague Puerto_Vallarta Pune Punta_Cana Punta_Cana_Hotel Queenstown Reykjavik Rio_de_Janeiro Riveria_Maya Rome Sacramento Saipan Salt_Lake_City San_Antonio San_Diego San_Diego_Hotel San_Francisco San_Jose San_Juan Santa_Cruz Santiago Santo_Domingo Seattle Sentosa Seoul Shanghai Sharm_el_Sheikh Shenzhen Singapore_Airport Singapore Singapore_Hotel Sioux_City_Hotel St._Louis St._Maarten St._Thomas Stockholm Surfers_Paradise Sydney Taichung Taipei Tampa Tampa_Hotel Tel_Aviv Tenerife Tijuana Tokyo_Uyeno-Eki Tokyo Toronto_SkyDome Toronto Tulsa_Hotel Vallarta_Hotel Vancouver Vancouver_Casino Venice Vienna Warsaw Washington Whistler Yankee_Stadium Yokohama Other]

end
